defaults:
  - visualization: default
  - task: ???
  - data: ???
  - debugging: default

num_workers: 0
batch_size: 2
cuda: 0
weight_name: "latest" # Used during resume, select with model to load from [miou, macc, acc..., latest]
enable_cudnn: True
checkpoint_dir: ??? # "{your_path}/outputs/2020-01-28/11-04-13" for example
model_name: ???
precompute_multi_scale: False # Compute multiscale features on cpu for faster training / inference
epochs: 1

pretty_print: True

wandb:
  project: ???
  log: True
  public: True

tracker_options: # Extra options for the tracker
  full_res: False
  make_submission: True

hydra:
  run:
    dir: ${checkpoint_dir}/calibrate


